"""Análise de Dados com Pandas e Matplotlib

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jKNaY_9EwK99fXk6UBmsBW0bXSwv3OQB
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/precos_carros_brasil.csv")
df = df.dropna()
coluna_preco = df.select_dtypes(include='number').columns[0]
fig, ax = plt.subplots()
ax.plot(df.index, df[coluna_preco], color="red", linewidth=2, label="Valores")
ax.set_title("Variação dos valores dos carros")
ax.set_xlabel("Índice")
ax.set_ylabel("Valor")

plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/precos_carros_brasil.csv")
df = df.dropna()
colunas_texto = df.select_dtypes(include='object').columns
if len(colunas_texto) > 0:
    coluna = colunas_texto[0]
else:
    coluna = df.columns[0]
dados = df[coluna].value_counts().head(5)
fig, ax = plt.subplots()
ax.bar(dados.index, dados.values, color="green")
ax.set_title("Frequência das categorias")
ax.set_xlabel("Categoria")
ax.set_ylabel("Quantidade")
ax.legend("Dados")

plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/precos_carros_brasil.csv")
df = df.dropna()
colunas_numericas = df.select_dtypes(include='number').columns
if len(colunas_numericas) > 0:
    coluna = colunas_numericas[0]
else:
    raise ValueError("Não há colunas numéricas no dataset")
fig, ax = plt.subplots()
ax.hist(df[coluna], bins=20, color="purple")
ax.set_title("Distribuição dos valores")
ax.set_xlabel("Valores")
ax.set_ylabel("Frequência")

plt.show()